const itemPool = [

    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },
    // { name: "滤毒罐", w: 1, h: 1, rarity: "green", image: "/assets/images/obj-green/滤毒罐.png" },




    { name: "信号棒", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/信号棒.png" },
    { name: "后妃耳环", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/后妃耳环.png" },
    { name: "海岛弯刀", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/海岛弯刀.png" },
    { name: "资料：军事情报", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/资料：军事情报.png" },
    { name: "橘味能量凝胶", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/橘味能量凝胶.png" },
    { name: "生津柠檬茶", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/生津柠檬茶.png" },
    { name: "间谍笔", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/间谍笔.png" },
    { name: "GS5手柄", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/GS5手柄.png" },
    { name: "电子干扰器", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/电子干扰器.png" },
    { name: "内存条", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/内存条.png" },
    { name: "固态硬盘", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/固态硬盘.png" },
    { name: "高级燃料", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/高级燃料.png" },
    { name: "聚乙烯纤维", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/聚乙烯纤维.png" },
    { name: "鳄鱼血样", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/鳄鱼血样.png" },
    { name: "高级情报凭证", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/高级情报凭证.png" },
    { name: "鳄鱼蛋", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/鳄鱼蛋.png" },
    { name: "植物样本", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/植物样本.png" },
    { name: "图腾箭矢", w: 1, h: 1, rarity: "purple", image: "/assets/images/obj-purple/图腾箭矢.png" },
    { name: "燃气喷灯", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/燃气喷灯.png" },
    { name: "阿萨拉特色提灯", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/阿萨拉特色提灯.png" },
    { name: "人工膝关骨", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/人工膝关骨.png" },
    { name: "阿萨拉卫队档案", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/阿萨拉卫队档案.png" },
    { name: "无菌敷料包", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/无菌敷料包.png" },
    { name: "黄金饰章", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/黄金饰章.png" },
    { name: "阿萨拉特色酒壶", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/阿萨拉特色酒壶.png" },
    { name: "特种钢", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/特种钢.png" },
    { name: "防弹陶瓷", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/防弹陶瓷.png" },
    { name: "钛合金", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/钛合金.png" },
    { name: "高出力粉碎钳", w: 1, h: 2, rarity: "purple", image: "/assets/images/obj-purple/高出力粉碎钳.png" },
    { name: "军用露营灯", w: 1, h: 3, rarity: "purple", image: "/assets/images/obj-purple/军用露营灯.png" },
    { name: "声卡", w: 2, h: 1, rarity: "purple", image: "/assets/images/obj-purple/声卡.png" },
    { name: "收音机", w: 2, h: 1, rarity: "purple", image: "/assets/images/obj-purple/收音机.png" },
    { name: "HIFI声卡", w: 2, h: 1, rarity: "purple", image: "/assets/images/obj-purple/HIFI声卡.png" },
    { name: "广角镜头", w: 2, h: 1, rarity: "purple", image: "/assets/images/obj-purple/广角镜头.png" },
    { name: "犄角墙饰", w: 2, h: 1, rarity: "purple", image: "/assets/images/obj-purple/犄角墙饰.png" },
    { name: "便携生存套组", w: 2, h: 1, rarity: "purple", image: "/assets/images/obj-purple/便携生存套组.png" },
    { name: "便携音响", w: 2, h: 1, rarity: "purple", image: "/assets/images/obj-purple/便携音响.png" },
    { name: "电动马达", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/电动马达.png" },
    { name: "咖啡机", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/咖啡机.png" },
    { name: "自旋型手锯", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/自旋型手锯.png" },
    { name: "ASOS电脑主板", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/ASOS电脑主板.png" },
    { name: "加密路由器", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/加密路由器.png" },
    { name: "离心机", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/离心机.png" },
    { name: "血压仪", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/血压仪.png" },
    { name: "中级子弹生产零件", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/中级子弹生产零件.png" },
    { name: "生化培养箱", w: 2, h: 2, rarity: "purple", image: "/assets/images/obj-purple/生化培养箱.png" },
    { name: "仪典匕首", w: 3, h: 2, rarity: "purple", image: "/assets/images/obj-purple/仪典匕首.png" },
    { name: "马赛克灯台", w: 2, h: 3, rarity: "purple", image: "/assets/images/obj-purple/马赛克灯台.png" },
    { name: "军用热像仪", w: 2, h: 3, rarity: "purple", image: "/assets/images/obj-purple/军用热像仪.png" },
    { name: "电动车电池", w: 3, h: 2, rarity: "purple", image: "/assets/images/obj-purple/电动车电池.png" },


    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    { name: "滤毒罐", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/滤毒罐.png" },
    { name: "优秀雇员奖杯", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/优秀雇员奖杯.png" },
    { name: "卫队金扳指", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/卫队金扳指.png" },
    { name: "渡鸦项坠", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/渡鸦项坠.png" },
    { name: "海鲜粥罐头", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/海鲜粥罐头.png" },
    { name: "营养粥罐头", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/明日方舟OST-1.png" },
    { name: "明日方舟OST-1", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/营养粥罐头.png" },
    { name: "三角蚌小珍珠", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/三角蚌小珍珠.png" },
    { name: "滤毒罐", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/滤毒罐.png" },
    { name: "手机", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/手机.png" },
    { name: "镜头", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/镜头.png" },
    { name: "固体燃料", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/固体燃料.png" },
    { name: "脑机控制端子", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/脑机控制端子.png" },
    { name: "纯金打火机", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/纯金打火机.png" },
    { name: "咖啡", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/咖啡.png" },
    { name: "血氧仪", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/血氧仪.png" },
    { name: "静脉定位器", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/静脉定位器.png" },
    { name: "亮闪闪的海盗金币", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/亮闪闪的海盗金币.png" },
    { name: "可编程处理器", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/可编程处理器.png" },
    { name: "数码相机", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/数码相机.png" },
    { name: "资料：设计图纸", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/资料：设计图纸.png" },
    { name: "CPU", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/CPU.png" },
    { name: "高速固态硬盘", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/高速固态硬盘.png" },
    { name: "阿萨拉特色酒杯", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/阿萨拉特色酒杯.png" },
    { name: "功绩勋章", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/功绩勋章.png" },
    { name: "八音盒", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/八音盒.png" },
    { name: "体内除颤仪", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/体内除颤仪.png" },
    { name: "心灵感应.魔方", w: 1, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/心灵感应.魔方.png" },
    { name: "卫星电话", w: 1, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/卫星电话.png" },
    { name: "克小圈", w: 1, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/克小圈.png" },
    { name: "心脏支架", w: 1, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/心脏支架.png" },
    { name: "紫外线灯", w: 1, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/紫外线灯.png" },
    { name: "哈夫克机密档案", w: 1, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/哈夫克机密档案.png" },
    { name: "“蓝宝石”龙舌兰", w: 1, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/“蓝宝石”龙舌兰.png" },
    { name: "盒装挂耳咖啡", w: 1, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/盒装挂耳咖啡.png" },
    { name: "金枝桂冠", w: 2, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/金枝桂冠.png" },
    { name: "赛伊德的手弩", w: 2, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/赛伊德的手弩.png" },
    { name: "军用弹道计算机", w: 2, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/军用弹道计算机.png" },
    { name: "座钟", w: 2, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/座钟.png" },
    { name: "单反相机", w: 2, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/单反相机.png" },
    { name: "军用炸药", w: 2, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/军用炸药.png" },
    { name: "移动电缆", w: 2, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/移动电缆.png" },
    { name: "军用望远镜", w: 2, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/军用望远镜.png" },
    { name: "卫星信号通讯仪器", w: 2, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/卫星信号通讯仪器.png" },
    { name: "燃料电池", w: 2, h: 3, rarity: "yellow", image: "/assets/images/obj-yellow/燃料电池.png" },
    { name: "珠宝头冠", w: 3, h: 1, rarity: "yellow", image: "/assets/images/obj-yellow/珠宝头冠.png" },
    { name: "大型电台", w: 3, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/大型电台.png" },
    { name: "高级子弹生产零件", w: 3, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/高级子弹生产零件.png" },
    { name: "本地特色首饰", w: 3, h: 2, rarity: "yellow", image: "/assets/images/obj-yellow/本地特色首饰.png" },
    { name: "阵列服务器", w: 4, h: 3, rarity: "yellow", image: "/assets/images/obj-yellow/阵列服务器.png" },


    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
      
    
    { name: "名贵机械表", w: 1, h: 1, rarity: "red", image: "./assets/images/obj-red/mgjxb.png" },
    { name: "怀表", w: 1, h: 1, rarity: "red", image: "./assets/images/obj-red/hb.png" },
    { name: "至纯源石", w: 1, h: 1, rarity: "red", image: "./assets/images/obj-red/zcys.png" },
    { name: "实验数据", w: 1, h: 1, rarity: "red", image: "./assets/images/obj-red/sysj.png" },
    { name: "量子存储", w: 1, h: 1, rarity: "red", image: "./assets/images/obj-red/lzcc.png" },
    { name: "“钻石”鱼子酱", w: 1, h: 1, rarity: "red", image: "./assets/images/obj-red/zsyzj.png" },
    { name: "万足金条", w: 1, h: 2, rarity: "red", image: "./assets/images/obj-red/wzjt.png" },
    { name: "奥莉薇娅香槟", w: 1, h: 2, rarity: "red", image: "./assets/images/obj-red/xb.png" },
    { name: "高级咖啡豆", w: 1, h: 2, rarity: "red", image: "./assets/images/obj-red/gjkfd.png" },
    { name: "棘龙爪化石", w: 2, h: 1, rarity: "red", image: "./assets/images/obj-red/hs.png" },
    { name: "显卡", w: 2, h: 1, rarity: "red", image: "./assets/images/obj-red/xk.png" },
    { name: "军用控制终端", w: 2, h: 1, rarity: "red", image: "./assets/images/obj-red/jykzzd.png" },
    { name: "“天圆地方”", w: 2, h: 2, rarity: "red", image: "./assets/images/obj-red/tydf.png" },
    { name: "黄金瞪羚", w: 2, h: 2, rarity: "red", image: "./assets/images/obj-red/hjdl.png" },
    { name: "摄影机", w: 2, h: 2, rarity: "red", image: "./assets/images/obj-red/syj.png" },
    { name: "呼吸机", w: 2, h: 2, rarity: "red", image: "./assets/images/obj-red/hxj.png" },
    { name: "强化碳纤维板", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/qhtxwb.png", price: "27847500" },
    { name: "ECMO", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/ECMO.png" },
    { name: "“纵横”", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/zh.png" },
    { name: "复苏呼吸机", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/fshxj.png" },
    { name: "便携军用雷达", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/bxjyld.png" },
    { name: "扫地一体机器人", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/sdjqr.png" },
    { name: "绝密服务器", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/jmfwq.png" },
    { name: "万金泪冠", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/wjlg.png" },
    { name: "主战坦克模型", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/zztkmx.png" },
    { name: "军用炮弹", w: 3, h: 2, rarity: "red", image: "./assets/images/obj-red/jypd.png" },
    { name: "装甲车电池", w: 3, h: 2, rarity: "red", image: "./assets/images/obj-red/zjcdc.png" },
    { name: "步战车模型", w: 3, h: 2, rarity: "red", image: "./assets/images/obj-red/bzcmx.png" },
    { name: "云存储阵列", w: 3, h: 2, rarity: "red", image: "./assets/images/obj-red/ycczl.png" },
    { name: "军用信息终端", w: 3, h: 2, rarity: "red", image: "./assets/images/obj-red/jyxxzd.png" },
    { name: "飞行记录仪", w: 3, h: 2, rarity: "red", image: "./assets/images/obj-red/fxjly.png" },
    { name: "微型反应炉", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/wxfyl.png" },
    { name: "曼德尔超算单元", w: 3, h: 3, rarity: "red", image: "./assets/images/obj-red/mdecsdy.png" },
    { name: "克劳迪乌斯半身像", w: 2, h: 3, rarity: "red", image: "./assets/images/obj-red/bsx.png" },
    { name: "雷斯的留声机", w: 2, h: 3, rarity: "red", image: "/assets/images/obj-red/lsdlsj.png" },
    { name: "医疗机械人", w: 2, h: 3, rarity: "red", image: "./assets/images/obj-red/yljxr.png" },
    { name: "滑膛枪", w: 4, h: 1, rarity: "red", image: "./assets/images/obj-red/htq.png" },
    { name: "高速磁盘阵列", w: 4, h: 3, rarity: "red", image: "./assets/images/obj-red/gscpzl.png" },
    { name: "动力电池组", w: 4, h: 3, rarity: "red", image: "./assets/images/obj-red/dldcz.png" },
    { name: "刀片服务器", w: 3, h: 4, rarity: "red", image: "./assets/images/obj-red/dpfwq.png" },
    { name: "浮力补偿设备", w: 3, h: 4, rarity: "red", image: "./assets/images/obj-red/flbcsb.png" },
    { name: "非洲之心", w: 1, h: 1, rarity: "red", image: "./assets/images/obj-red/fzzx.png" },
    { name: "海洋之泪", w: 1, h: 1, rarity: "red", image: "./assets/images/obj-red/hyzl.png" },

    // { name: "总裁会议室", w: 1, h: 1, rarity: "key", image: "./assets/images/obj-red/zchys.png" },

]